language: python

# execute lint and py38 as separate CI processes
matrix:
  include:
    - python: 3.8
      dist: bionic
      env: TOXENV=py38
    - python: 3.8
      dist: bionic
      env: TOXENV=lint

# install tox
install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install tox
  - pip install codecov tox
  - sudo apt-get install mosquitto
  - sudo apt-get install influxdb
  - sudo service influxdb start
# command to run tests
script:
  - tox
# Upload coverage report to 'Codecov'
after_script:
  - codecov --token=3717ca2a-9926-4391-9d2b-0c72fc598488